# Generated by Django 5.1.4 on 2025-01-22 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='item',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='ordered',
            new_name='order',
        ),
    ]
