# Generated by Django 5.1.4 on 2025-01-22 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_item_orderitem_item_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='ordered',
        ),
    ]
